version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank-churn-api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    networks:
      - monitoring-network
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.30.3
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - monitoring-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:8.2.2
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/simple_dashboard.json
    networks:
      - monitoring-network
    depends_on:
      - prometheus
    restart: unless-stopped

networks:
  monitoring-network:
    driver: bridge