{
 "title": "FastAPI Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "3s",
 "panels": [
  {
   "title": "Request per minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(http_requests_total[1m]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p50",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "clocks" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(http_request_duration_seconds_bucket{handler!=\"none\"}[30s]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Requests under 100ms",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "increase(http_request_duration_seconds_bucket{le=\"0.1\"}[1m]) \n/ ignoring (le) increase(http_request_duration_seconds_count[1m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p90",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 6 },
   "yaxes": [
    { "format": "clocks" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(http_request_duration_seconds_bucket{handler!=\"none\"}[30s]))",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Model Predictions",
   "type": "graph",
   "description": "Number of predictions made by the model",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prediction_count_total[1m])",
     "legendFormat": "Predictions per minute"
    },
    { "expr": "prediction_count_total", "legendFormat": "Total predictions" }
   ]
  }
 ]
}